stages:
  clean_data:
    cmd: python src/clean_data.py
    deps:
      - data/train.csv
      - data/train.csv.dvc
      - params.yaml
    outs:
      - data/preprocess/preprocessed_train.csv

  # train_model:
  #   cmd: python src/train.py
  #   deps:
  #     - data/preprocess/preprocessed_train.csv
  #     - params.yaml
  #   outs:
  #     - model/model.pkl

  # evaluate_model:
  #   cmd: python src/evaluate.py
  #   deps:
  #     - model/model.pkl
  #     # - data/preprocess/preprocess_test.csv